### ISSUE TITLE
[Feature Request] Vertical Movestones 

### ISSUE THREAD

**Issue by qwrwed** [minetest-mods/mesecons#261]
I've seen this mentioned a lot on the forums; vertical movestones and sticky vertical movestones would mainly be useful for elevators, but I'm sure there are other uses too.
It would also be useful if they can stick to other movestones, so you could have square movestone platforms all moving in one direction or the other.

**Comment by C1ffisme** [comment]
I'm sure this is possible...

**Comment by Jeija** [comment]
If someone implements this well, I will merge this feature. Personally, I just don't have the time for that.

**Comment by numberZero** [comment]
@C1ffisme, everything is possible. But I think digiline movestones (as on the `Survival in Ethereal` server, but less buggy than I remember) would be way better. That should not be difficult to implement as you don’t even need to check which side is powered, and such devices would be way easier to use.
