### ISSUE TITLE
Piston arm can by dropped by exploding it with a TNT

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#291]
It is possible to make the piston arm drop as an item (and thus collectible):

* Use Minetest Game
* Place some pistons somewhere
* Activate them all so that the arm is out
* Place and ignite TNT nearby

If you're lucky, you will soon find some dropped piston arms lying around.

I think this bug could be easiest fixed if the drop of the piston arm is disabled (`drop = ""`).

**Comment by cheapie** [comment]
I'll take a look at fixing this once the fate of #302 is known (as I don't want to cause any merge conflicts).
