### ISSUE TITLE
Pistons are not rotated correctly by screwdriver

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#292]
You can use the screwdriver from Minetest Game to screw up active pistons. You can rotate the piston arm and the piston itself seperately, which looks odd.
Minetest Game has API support for special screwdriver handling.

One possible bugfix would be to disable rotation for the piston arm completely and add special rotation code for the piston itself, if its arm is out (trying to rotate both piston and piston arm, if possible).

**Comment by Jeija** [comment]
I don't think adding special code for rotating the piston is worth the effort. I'd say it is acceptable to just completely disable rotation in this case.

**Comment by MahzunGozler** [comment]
I encounter the issue too and notice something :
When you move an extended piston with a screwdriver, you move only the piston and not the extended part indeed. Then if you break the piston, the extended arm will remain placed and become unbreakable, you can just rotate it with the screwdriver. World Edit was used to remove it.

I propose a simple (I think) bugfix : give the possibility to rotate a piston ONLY if the arm is retracted.
