### ISSUE TITLE
Mesecons nodes can be destroyed by cave generator

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#295]
I noticed that many Mesecons nodes do not have `is_ground_content = false` set (default is `true`). This means, all those nodes are possible victims for the cave generator.
Please add `is_ground_content = false` to all nodes.

**Comment by Jeija** [comment]
I'm not an expert on this, but shouldn't the cave generator only add caves when emerging new mapblocks? Then why does this need to be set on nodes that don't occur naturally?

I have noticed that pretty much every node in minetest_game has `is_ground_content = false` set, but is this really necessary (can you give an example scenario to help me understand)?

**Comment by Wuzzy2** [comment]
Paramat says it is a good idea to always set `is_ground_content` correctly, because of `on_generated` (Lua) map generators.
For example, a village mod might add some mesecons nodes, but if another cave-generating mod is added, this cave generator might “attack” the mesecons since `is_ground_content` is left to `true`.

Rule-of-thumb examples on how to use `is_ground_content`:
* Stuff of which the ground is made of and in which you would expect caves gets `is_ground_content=true` (default): Dirt, sand, gravel, limestone, sandstone, small unimportant plants (e.g. grass), etc.
* Artificial stuff gets `is_ground_content=false`: Chests, armor stand, furnace, brick block (that is, non-natural things which may have been crafted and placed by a player) and I guess probably all nodes added by Mesecons
* If a node does not really fit into both categories, just ask yourselves if the cavegen is allowed to destroy it.

**Comment by DS-Minetest** [comment]
I wonder why some nodes have `is_ground_content` set to `true`: https://github.com/minetest-mods/mesecons/search?utf8=%E2%9C%93&q=is_ground_content&type=

**Comment by numberZero** [comment]
Probably due to some oversight =) Thanks for spotting that)
