### ISSUE TITLE
Mesecons can be rotated

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#297]
You can use the screwdriver to rotate the mesecons themselves. I am pretty sure this is unintentional.

The Minetest Game API allows to handle (and prevent) screwdriver events, see `game_api.txt`.

**Comment by numberZero** [comment]
Insulated mesecons can be rotated wrongly:
![screenshot_20171015_171046](https://user-images.githubusercontent.com/7352626/31585546-47241dc4-b1cc-11e7-9815-f76241601b01.png)

**Comment by DS-Minetest** [comment]
Hm, the insulated mesecons wires just need better rules, that would give great possibilities (but would also be maybe a bit cheaty).

**Comment by numberZero** [comment]
No way, unless you change its model (but I can’t even imagine how could it look like, as mesecons, unlike `technic` cables, aren’t centered but lie on the ground normally).

**Comment by DS-Minetest** [comment]
I mean to change the rules (function) so, that the top mese in your screenshot would be powered.

**Comment by numberZero** [comment]
@DS-Minetest I understood. But that would look *too* weird. (Imagine there were not mese blocks, but conventional wires).

**Comment by DS-Minetest** [comment]
Those woudln't connect. Afaik, both need a rule that points to the other's pos.

**Comment by numberZero** [comment]
![screenshot_20171021_173557](https://user-images.githubusercontent.com/7352626/31852786-d5da354e-b686-11e7-942f-62acf613b1f0.png)
@DS-Minetest What and how would you fix here?

**Comment by DS-Minetest** [comment]
Oh, I see.
So, rotate simple should be used.
