### ISSUE TITLE
Alternative piston sound

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/mesecons#305]
The current piston sounds sound a lot like the power locks on a car or something to me. While there's nothing wrong with that, I think that since they act like solenoids, maybe they should sound like them too.

So, I was thinking maybe they could use sounds like these:
[https://cheapiesystems.com/media/piston_extend.ogg](https://cheapiesystems.com/media/piston_extend.ogg)
[https://cheapiesystems.com/media/piston_retract.ogg](https://cheapiesystems.com/media/piston_retract.ogg)

Note that these sounds, in their present state, are for demonstration only and are not licensed under appropriate terms to be included in the mod. If the decision is made to change the sounds, I can attempt to find some that are under a suitable license.

**Comment by sofar** [comment]
Not a bad start. I like these sounds because they're very short, but it may be cool to have the hydrolic/pneumatic hiss sound last a bit longer to get a bit of the steam-age atmosphere.

"click-pshhhhh" "clack-pshhhhh"

**Comment by cheapie** [comment]
I've always thought of the pistons as being some kind of electromagnetically-driven device, not so much hydraulic or pneumatic. I could, I suppose, have a bit more of the "mains hum" in the extend sound, which might make it sound a bit more "impressive".

**Comment by cheapie** [comment]
OK, here's one with a bit of hum/buzz in it:
[https://cheapiesystems.com/media/piston_extend2.ogg](https://cheapiesystems.com/media/piston_extend2.ogg)

**Comment by DS-Minetest** [comment]
That one sounds more like if you give power to something.
I like the current piston sound.

**Comment by numberZero** [comment]
Feel free to reopen if have something to add.
