### ISSUE TITLE
Remove tell command from mesecons_commandblock

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#310]
I suggest to remove the `tell` server command from the command block mod.

Reason: `msg` is a builtin server command and does exactly the same thing, so `tell` is completely redundant.

Possible problem: Might break some existing mesecons builds which use command blocks and the tell command.
Possible solution: An LBM which rewrites “tell” to “msg” commands white not screwing up the syntax.

**Comment by numberZero** [comment]
Any opinions on this?
@DS-Minetest please explain.

**Comment by numberZero** [comment]
Sorry, I though `tell` is a command block internal command. Didn’t know it registers that as a chat command. That’s definitely redundant.

It may be OK to deprecate `tell` and later remove it. But `say` should be renamed as well then, as `say` and `msg` aren’t a pair like `say` and `tell`.

Alternatively, both `say` and `tell` may be made command block built-in commands, maybe with altered semantics (different text color?).

**Comment by DS-Minetest** [comment]
Removing `tell` or any other commandblock chatcommand could break some constructions in worlds.
Also there are some differences between `tell` and `msg`.
<details><summary>registrations of tell and msg</summary>

https://github.com/minetest-mods/mesecons/blob/c73b451f9bce329fb1cfd48f68e9a581fa2f8930/mesecons_commandblock/init.lua#L10-L24

https://github.com/minetest/minetest/blob/a4f41e7bfc6c2d823eab1465258617cb033a452c/builtin/game/chatcommands.lua#L963-L982

</details>
`tell` doesn't require any priv, msg needs shout. So if you have no shout, you can only communicate directly via `tell`.
Also a `tell` message looks different from a `msg` command. Imagine you fall into a mesecons trap and see in the chat that you got a pm.

**Comment by Wuzzy2** [comment]
So the point of `tell` is to send arbitrary text to a player? OK, I can see the reason for this now. I retract my argument now that `tell` is redundant.

I no longer think this suggestion is important. Feel free to close.

**Comment by numberZero** [comment]
> `tell` doesn't require any priv, msg needs shout. So if you have no shout, you can only communicate directly via `tell`.

Hmm, interesting... That means there is a point to keep them as chat commands and not making them command block built-ins. But that certainly should be documented.
