### ISSUE TITLE
Breaking a rotated extended piston create an unbreakable extended arm

### ISSUE THREAD

**Issue by MahzunGozler** [minetest-mods/mesecons#314]
Over the issue #292 there is a biggest problem which is really a bug

When you move an extended piston with a screwdriver, you move only the piston and not the extended part indeed. Then if you break the piston, the extended arm will remain placed and become unbreakable, you can just rotate it with the screwdriver. World Edit was used to remove it.

![bug_rotating_piston](https://cloud.githubusercontent.com/assets/18640683/22113659/4bfa9e92-de67-11e6-9c9a-0298cbbe5591.png)

I propose a simple (I think) bugfix : give the possibility to rotate a piston ONLY if the arm is retracted.

**Comment by numberZero** [comment]
@MahzunGozler Test #302

**Comment by DS-Minetest** [comment]
Piston rotating now also works with extended ones and arms without base can be removed with screwdriver.
