### ISSUE TITLE
FPGA: more registers

### ISSUE THREAD

**Issue by sfan5** [minetest-mods/mesecons#317]
~~building a compact adder would require
`((~a & ~c & b) | (~a & ~b & c) | (~c & ~b & a)) | (a & b & c)`
in a single FPGA which needs 13 registers~~

sometimes more registers might be nice

**Comment by numberZero** [comment]
er, what’s about a^b^c ?
(just noticed that you use `b` in one place and `d` in others, assuming that’s not intentional)

**Comment by sfan5** [comment]
that's exactly what i needed, logic gates are hard :frowning_face:

**Comment by DS-Minetest** [comment]
Perhaps add buttons to switch to other sides?

**Comment by cheapie** [comment]
Does anyone have an actual use case for this? A half adder doesn't need any registers, and a full adder won't fit in one chip (not enough pins) anyway.
