### ISSUE TITLE
Nodebox of insulated wires reaches into node below

### ISSUE THREAD

**Issue by sfan5** [minetest-mods/mesecons#319]
as seen here 
![screenshot_20170129_204644](https://cloud.githubusercontent.com/assets/1042418/22408353/e376cb52-e677-11e6-9210-1546f940f41b.png)

This causes some surprising behaviors when trying to place a nice below or next to the wire

![screenshot_20170129_204445](https://cloud.githubusercontent.com/assets/1042418/22408372/22ced4d4-e678-11e6-86c6-a7698ecc093f.png)
→ node is placed one too far down

![screenshot_20170129_204627](https://cloud.githubusercontent.com/assets/1042418/22408375/2cee51ba-e678-11e6-866e-2486457f908d.png)
→ node is placed diagonally down (instead of next to the wire)

**Comment by DS-Minetest** [comment]
I recognized this when I made the crossing mesh, too.
But it seemed good like this.
- Why should it be changed? Players are ok with it.
- If it would be further up, it wouldn't connect correctly with uninsulated mesecon wire.

Well, perhaps the selection box should be changed.

**Comment by VanessaE** [comment]
I did the nodebox this way in order to make insulated wires match up properly with bare wires.

**Comment by DS-Minetest** [comment]
> → node is placed diagonally down (instead of next to the wire)

This only happens if you look at the down part of the selection box. Ergo this is no problem.

The only problem, I see here is 
> → node is placed one too far down

But this is very trivial.

**Comment by sfan5** [comment]
> This only happens if you look at the down part of the selection box. Ergo this is no problem.

This is very confusing if you don't know about this and accidentally point at the lower part, of course this is a problem.

**Comment by DS-Minetest** [comment]
But you can't even point at the lower part if you placed it on another node.

**Comment by sfan5** [comment]
> But you can't even point at the lower part if you placed it on another node.

I often place insulated wires free floating into the air

> Also other mods have such problems, too. Players are habituated with this.

That does not legitimize having such problems in mods

**Comment by DS-Minetest** [comment]
> That does not legitimize having such problems in mods

But it makes them more trivial.

Let's stop that unneeded discussion if there is a problem or not. There definitely is a problem. The question is how to fix it.

**Comment by DS-Minetest** [comment]
>Larger nodebox causes z-fighting

Do you mean than the faces which go into another node can z-fight with faces of the other node?
Maybe there should be offsets to all these faces.

**Comment by numberZero** [comment]
@DS-Minetest They would fight, wouldn’t the offset be added already. See my comments in the code of #431.

**Comment by DS-Minetest** [comment]
>offset be added already

The offset is only at the ends of the wires.
Are those even necessary btw.? With backface_culling you won't ever see both sides at once.

**Comment by numberZero** [comment]
I marked the area that would z-fight without the offset:
![z-fighting](https://user-images.githubusercontent.com/7352626/45258258-49042780-b3bd-11e8-8d51-489c15f1fbf3.png)

**Comment by DS-Minetest** [comment]
Ah, I see, thanks.

But I think, offset is needed on more sides:
![screenshot_20180908_224830](https://user-images.githubusercontent.com/7613443/45258556-f1b08800-b3b9-11e8-9e0e-c89bfbb01403.png)
There might be mods that add nodes with such nodeboxes.
The only faces which don't need any offset are the ones that are completely inside the normal 1³ box (in this case the top face only). If z-fighting occurs there, it's the fault of the other node.
The only problematic I see is that another mod registers a node with a box that leaves the 1³ space and gives it the same offset which might happen.
