### ISSUE TITLE
FPGA: Doesn't overheat

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/mesecons#320]
Even if I connect two pins and set one to be the inverse of the other, the FPGA won't overheat and instead just sits there oscillating (and making the server lag a bit).

**Comment by numberZero** [comment]
... and the client lag a lot... (at least a short-circuited NOT-gate does that)
Overheating is a pain as it works poorly (see #309), sometimes the heat level is not reset. But it is necessary anyway.

@sfan5 that should be easy to fix

**Comment by numberZero** [comment]
@DS-Minetest
