### ISSUE TITLE
Add more lightstone colors

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#323]
Any chance there will be more lightstone colors to match some of the missing Minetest Game dye colors? Would a PR have a chance?

* White
* Orange
* Pink
* Violet
* Cyan
* Magenta

(only bright colors have been chosen)

If not, I might release a separate mod. However, the lightstone API appears to be broken (I can't add lightstones from external mods).

**Comment by VanessaE** [comment]
If you to the effort of adding more lightstone colors, you should consider adding [cheapie's RGBlightstone](https://github.com/cheapie/rgblightstone) mod and doing some creative coding to use it to supersede the existing colors.

**Comment by numberZero** [comment]
cyan and magenta, at least, to match yellow. and probably orange and violet to make a rainbow and not just a color ring.
RGBlightstone is nice to have but sometimes you would prefer something simpler.

**Comment by DS-Minetest** [comment]
- The RGBlightstone mod needs digilines, not only to be installed but also to be used by the players. Many players won't know enough about digilines to use it. (Btw. there's also the [colour_carrier](https://github.com/HybridDog/colour_carrier) mod.)
=> Having more different lightstones would be good.

- A contra point is that lightstones are not used for art but to see some different nodes activated and deactivated. Does anybody really want to use so many different lightstones?

**Comment by Jeija** [comment]
I'd certainly agree to adding white, cyan and magenta so that our selection of colors makes more sense. Other colors depend on whether there is demand for it or not - I haven't really kept current with minetest mod development, but why couldn't someone use [Bobblocks](https://github.com/minetest-mods/BobBlocks) as a simple solution instead?

**Comment by VanessaE** [comment]
Well if you're going to add more colors, you should switch them over to use hardware coloring.  Only one or two textures would be needed that way, and if you use param2 to colorize, then you only need one node and some creative code.

**Comment by DS-Minetest** [comment]
> one node

It would be two nodes, on and off. Giving a node a bright color doesn't make it totally seem to be on.

**Comment by VanessaE** [comment]
Correct.  That was a brain-o. :)

**Comment by VanessaE** [comment]
@Jeija as for Bobblocks, actually that uses hardware coloring, so it would be a reasonable example of what I was talking about, though its textures don't lend themselves well to generic lightstones.

**Comment by numberZero** [comment]
954262d0164692fa03fe48e9bd439c8e570726fb
