### ISSUE TITLE
Node detectors sometimes get stuck in "on" state

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/mesecons#331]
Title pretty much says it all.

**Comment by DS-Minetest** [comment]
Could this perhaps be related to #325?

**Comment by numberZero** [comment]
Seems impossible. Make sure there is no ghoststone in front of the detector.

**Comment by VanessaE** [comment]
In my particular case, it's in a protected area and watching for wheat to grow.

**Comment by numberZero** [comment]
oh well, just remembered: before #330 it is possible to change scanname even in protected detector. wasn’t it changed to `air`?
otherwise, that must be a core bug causing ABMs to not run

**Comment by numberZero** [comment]
No answer since a while, closing.
