### ISSUE TITLE
Luacontroller and Microcontroller have the same recipe

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/mesecons#339]
This makes one or the other impossible to craft.

**Comment by DS-Minetest** [comment]
<details>
<summary>Suggestion:</summary>
Add two crafting recipes to craft the controller into the other one.
</details>

**Comment by numberZero** [comment]
Or just remove microcontroller crafting recipe. It is deprecated, why is it still craftable?

**Comment by C1ffisme** [comment]
@numberZero Because everyone related to Minetest, me included, has a little bit of a nostalgia problem. :stuck_out_tongue_closed_eyes:

**Comment by DS-Minetest** [comment]
@C1ffisme True, me too.
But also it's a feature and so, why should it be removed? Also with mesecons (no more minetest-mods-mesecons) as modpack, the parts can be deactivated. AFAIK there's a mesecons_microcontroller mod, it can also be deactivated.
<details>
<summary>An additional suggestion:</summary>

Add to the description of microcontroller something like core.colorize("#FF0000", "\nDeprecated").</details>

**Comment by C1ffisme** [comment]
@DS-Minetest The main reason why it should be removed is because it's old, and, AFAIK, nobody is going to maintain it. That brings up issues especially if Minetest 0.5.0 is going to "break mod compatibility". Plus, the lua controller uses a real language, and just for bonus points, the same language that the modding API is written in. If that's not a good way to introduce someone to programming, I dunno what is.

**Comment by sofar** [comment]
One easy solution would be to make a crafting recipe out of the lua controller to make a microcontroller, and vice versa.

**Comment by C1ffisme** [comment]
@sofar That's possible, and an easy solution, but what's the point of keeping the microcontroller anyway if the luacontroller is far superior? (and the microcontroller is more likely to break if nobody maintains the code)

**Comment by benrob0329** [comment]
Microcontroller has been replaced by FGPA afaik

**Comment by VanessaE** [comment]
Imho, the simplest solution is to delete the crafting recipe for the µC, and hide it from the creative inventory.   That way newer stuff is promoted and old maps still work.

**Comment by Brackston** [comment]
PR 351 seems to need both the lua's and the uController's itint.lua files to be changed. My PR only changed the uController and leave the lua controller alone.
Please see and comment. Thank you. 
This change has been tested and is currently running on a public server
#353
