### ISSUE TITLE
Pistons/movestones push static entities

### ISSUE THREAD

**Issue by qwrwed** [minetest-mods/mesecons#349]
Pistons and movestones push entities such as those displayed on [pedestals](https://forum.minetest.net/viewtopic.php?id=5600) or [armour stands](https://forum.minetest.net/viewtopic.php?t=4654), even if the display node isn't pushed. The moved entities remain after the display node is dug.

![screenshot_20170523_234934](https://cloud.githubusercontent.com/assets/2429893/26379993/e4ef3744-4013-11e7-88d2-b364fce5fb49.png)
![screenshot_20170523_234951](https://cloud.githubusercontent.com/assets/2429893/26379994/e63bf484-4013-11e7-982e-c8c9377c88a7.png)
![screenshot_20170523_235822](https://cloud.githubusercontent.com/assets/2429893/26379996/e76273d8-4013-11e7-9529-7692b8593dc5.png)

**Comment by DS-Minetest** [comment]
The mods should use `mesecon.register_mvps_unmov(objectname)` if they want their objects to be static.

**Comment by DS-Minetest** [comment]
Now mods can simply `mesecon.register_mvps_unmov` the entity and move it by themselves with `nodedef.mesecon.on_mvps_move`.
