### ISSUE TITLE
Separated mesecons wire does not turn off when connection to power source is destroyed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#352]
How to reproduce:

* Place a long straight line of mesecons
* Put a power plant at one end to activate the wire
* Near the center of the wire, detonate TNT

Expected result: The wire which is now separated from the power plant should turn off
Actual result: All wires stay turned on

Suspicion: This is not limited to TNT but also could happen when the wire is destroyed (not dug) in general.

Similar experiment: Same as before, but this time you *only* blow up the power plant. All wires stay turned on.

**Comment by DS-Minetest** [comment]
#356 maybe fixes the part with the TNT. Maybe an `on_destruct` should be added.

**Comment by numberZero** [comment]
Rotation is ignored as well; see #297

**Comment by numberZero** [comment]
TNT part is fixed. VoxelManip can’t be fixed, that’s the expected behavior: nothing around is told the change, even the light may not be updated.

If the bug appears again with anything other than VoxelManip, reopen this issue.
