### ISSUE TITLE
Piston with node doesn't push players/entities with most drawtypes

### ISSUE THREAD

**Issue by qwrwed** [minetest-mods/mesecons#361]
If you attach a node with a non-default drawtype to the end of a piston, it won't push entities, as shown below:

![screenshot_20170907_025221](https://user-images.githubusercontent.com/2429893/30142418-8c0e14fc-9378-11e7-9ab0-3c4fc5d62970.png)
![screenshot_20170907_025232](https://user-images.githubusercontent.com/2429893/30142420-901dea86-9378-11e7-88c1-360327bb1a56.png)

If there is no node or a full block node, the player/entity will be pushed as expected.

With a nodebox of any size or shape (or any other non-default drawtype e.g. raillike, plantlike), the node will simply clip through any players/entities standing on them, failing to push them up and potentially trapping them.

Edit: It seems that all nodes are treated as if they are full nodes, so if there is a 1/16th slab on a piston, it won't move the entity unless that entity is 2 nodes away from the piston, even if there is space in the adjacent node.

**Comment by qwrwed** [comment]
@DS-Minetest https://github.com/minetest-mods/mesecons/blob/36a6419481599c5b5ae2b43697722108fbc1d63d/mesecons_mvps/init.lua#L209 It seems the issue is in this line, but I'm not sure how it can be changed so that all items inside the stack are moved (this would resolve the issue). Would you be able to help with this?

**Comment by DS-Minetest** [comment]
I think, moving all objects in stack makes sense.
I'll look what I can do.
