### ISSUE TITLE
Pressure plate and solar panel don't power block directly below

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#369]
Presure plates and solar panels are weird. While they propagate power to the 4 adjacent blocks *below* themselves, they do *not* power the block directly beneath it (nor do they power the block 2 blocks beneath it; I'm not sure if this is intentional).

**Comment by Wuzzy2** [comment]
Nope.
The issue is not fixed. Solar panels and pressure plates still ignore the block directly below.

993fdedd8ccc21610efee00a08e102b38aa34b7e

**Comment by benrob0329** [comment]
You have to use vertical mesecon two blocks below a pressure plate iirc

**Comment by Wuzzy2** [comment]
This is pointless, you would just fall through the pressure plate as the vertical mesecons are non-walkable (and shouldn't be).

**Comment by Wuzzy2** [comment]
This doesn't work either. It also looks weird to have a pressure plate balancing on a thin mesecon. xD

**Comment by VanessaE** [comment]
so put mese blocks below it?

**Comment by benrob0329** [comment]
Not directly below,

```
BPB
BBB
mVm
```

**B**lock, **M**esecon, **V**ertical mesecon.

**Comment by Wuzzy2** [comment]
OK, this actually works.
