### ISSUE TITLE
Not all textures are 16x16 

### ISSUE THREAD

**Issue by tobyplowy** [minetest-mods/mesecons#375]
Why are not all textures 16x16?
It's very inconsistent :/

**Comment by DS-Minetest** [comment]
Pipeworks has some 32^2 (or even higher) textures, too.
Imo 32^2 is ok if a node needs more detail eg. because it has small faces.
However the high luacontroller texture is bad imo because it causes lag on dig.

**Comment by numberZero** [comment]
@tobyplowy which exactly? I know LuaC only.

> it causes lag on dig.

Well, maybe, as crack is laid over in a strange way. See https://github.com/minetest/minetest/issues/6108
