### ISSUE TITLE
buttons with param2 = 2 do not work

### ISSUE THREAD

**Issue by fireglow** [minetest-mods/mesecons#378]
Hi,
I'm at cc860acf8a4d0c7c0a8c814bdf0aceada72e2b56 (Oct 18 22:54:28 2017 +0300), server version 0.4.16 release.
Buttons with param2 = 2 do not work.
They do not transmit a signal to the connected mesecon.
The three other directions work fine.
Just tested on a server with only default and mesecons active.

**Comment by numberZero** [comment]
@fireglow f78937b
