### ISSUE TITLE
Falling nodes pushed by pistons over a gap won't fall

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/mesecons#389]
If you push a falling node (such as sand) above a hole, the falling node will refuse to fall, causing the node to float in mid-air until it is updated.

**Comment by DS-Minetest** [comment]
I wasn't able to reproduce this exactly. But falling nodes seem to float if you push them up.

**Comment by DS-Minetest** [comment]
@Wuzzy2 Does #392 fix it?

**Comment by Wuzzy2** [comment]
Yes.
