### ISSUE TITLE
Pistons stuck in on position

### ISSUE THREAD

**Issue by edbosne** [minetest-mods/mesecons#405]
Sometimes pistons get stuck in the on position.

You can test this with the unstable circuit in this screenshot. But I noticed it in an other construction.

![screenshot_20180502_205356](https://user-images.githubusercontent.com/25692804/39546344-fe17e3be-4e4b-11e8-9ee5-14b9fd490163.png)

The circuit are two sticky pistons. One is activated by a button, which then activates and other that cuts the source for the first.

Note that it is important to use a button. With a constant source it doesn't seem to block.

**Comment by numberZero** [comment]
See #406

**Comment by DS-Minetest** [comment]
Another construction where a piston gets stuck in position:
![screenshot_20180910_004448](https://user-images.githubusercontent.com/7613443/45269895-15490080-b496-11e8-92c4-49e70a1ba418.png)

**Comment by numberZero** [comment]
> See #406
