### ISSUE TITLE
print(event) causes error

### ISSUE THREAD

**Issue by nkruglikov** [minetest-mods/mesecons#407]
Hi, I experiment with the current version (https://github.com/minetest-mods/mesecons/commit/7013f2e5d47ff2d21fb66fe82966a34ece947eec) of mesecons.

When I tried to type `print(event)` in LuaController (an example from tutorial!), it displayed the following error:
```
Lua controller programming error: ...est/mods/mesecons-master/mesecons_luacontroller/init.lua:224: string.find: 'plain' (fourth parameter) must always be true in a Luacontroller
```

I guess the code somehow use the securified `find` function, but I can't detect the source of the problem yet.

**Comment by numberZero** [comment]
`print` inside the sandbox is `safe_print` in the LuaC `init.lua`; thus the call sequence is:

* `safe_print` (`mesecons_luacontroller/init.lua:200`) is called
* `dump` (`builtin/common/misc_helpers.lua:122`) is called at `mesecons_luacontroller/init.lua:201`
* `is_valid_identifier` (`builtin/common/misc_helpers.lua:52`) is called at `builtin/common/misc_helpers.lua:147`
* `(string):find` is called at `builtin/common/misc_helpers.lua:53`

That appears to be the only `:`-style call in `dump`, and can be easily fixed upstream. Try the following patch:
```patch
diff --git a/builtin/common/misc_helpers.lua b/builtin/common/misc_helpers.lua
index 23b00eafe..c0a6a0447 100644
--- a/builtin/common/misc_helpers.lua
+++ b/builtin/common/misc_helpers.lua
@@ -50,7 +50,7 @@ local keywords = {
 	["while"] = true,
 }
 local function is_valid_identifier(str)
-	if not str:find("^[a-zA-Z_][a-zA-Z0-9_]*$") or keywords[str] then
+	if not string_find(str, "^[a-zA-Z_][a-zA-Z0-9_]*$") or keywords[str] then
 		return false
 	end
 	return true
```
(The `string_find` is defined already, for “better performance”)

**Comment by sfan5** [comment]
IMO this is a bug in Mesecons sandbox, upstream can't be expected to adhere to some random sandbox' rules of what is safe.
When calling any of the builtin functions, execution should be transferred out of the sandbox (after parameters have been verified), so that function is not bound by the sandbox and can do whatever it wants.

The alternative is reimplementing everything within the `safe_` functions.

**Comment by numberZero** [comment]
Of course it’s Mesecons’ bug. I didn’t mean to blame MT, sorry. I only
meant that MT might not trigger that bug: there is only one place where
it uses `:` notation.

On the other hand, that’s `dump`, a function that is expected to accept
*any* kind of data, without any notion of validity; data with tricky
metatables is just one sort of that. But that may be hard to acheive,
e.g. numbers’ metatable is hard to circumvent (but easy to set using
the `debug` library, which is available even in secure mode).

В Tue, 29 May 2018 02:04:09 -0700
sfan5 <notifications@github.com> пишет:

> IMO this is a bug in Mesecons sandbox, upstream can't be expected to
> adhere to some random sandbox' rules of what is safe. When calling
> any of the builtin functions, execution should be transferred out of
> the sandbox (after parameters have been verified), so that function
> is not bound by the sandbox and can do whatever it wants.
> 
> The alternative is reimplementing everything within the `safe_`
> functions.
>
