### ISSUE TITLE
Double corner insulated wire suggestion

### ISSUE THREAD

**Issue by edbosne** [minetest-mods/mesecons#408]
Hi,

It seems to me that a double corner wire would make the mesecon insulated wires more complete. 

![other_wire](https://user-images.githubusercontent.com/25692804/40715231-cc1781e6-63fc-11e8-803b-6b93e367347d.png)

This would be specially useful when wanting to shift to the side a couple of parallel wires in a compact way. For example.

![screenshot_20180530_111256](https://user-images.githubusercontent.com/25692804/40715401-5a10b22e-63fd-11e8-8d26-838121d8a273.png)

What do you think of this?

**Comment by numberZero** [comment]
Nice idea, but... how would you do that in Mesecons style? I.e. without diagonal parts.

OTOH, it may be better to add [TTD-style](https://wiki.openttd.org/File:Priority_Merge.png) wires... These would fit the boxy world better than (pseudo-)round ones IMO.

**Comment by numberZero** [comment]
![screenshot_20200802_101139](https://user-images.githubusercontent.com/7352626/89117912-3bbd1e00-d4aa-11ea-8a41-4784c7fa8a48.png)

Possible looks:
1. ![screenshot_20200802_102203](https://user-images.githubusercontent.com/7352626/89117918-3fe93b80-d4aa-11ea-84cb-8a16a383e63d.png)
2. ![screenshot_20200802_101205](https://user-images.githubusercontent.com/7352626/89117915-3d86e180-d4aa-11ea-8ba2-5d0a81d6004f.png)
3. ![screenshot_20200802_101227](https://user-images.githubusercontent.com/7352626/89117916-3f50a500-d4aa-11ea-8af7-a595d11e029b.png)

**Comment by VanessaE** [comment]
I think, since other Mesecons items occasionally allow non-orthogonal shapes, the wire pair should actually be diagonal in this case.  The stair-step shapes presented above could confuse people.

**Comment by numberZero** [comment]
![screenshot_20200806_013410](https://user-images.githubusercontent.com/7352626/89470756-33543400-d785-11ea-84ec-2ee934b0d11c.png)

**Comment by VanessaE** [comment]
That looks good to me at least :smile:

**Comment by numberZero** [comment]
Note that proper diagonals (without axis-aligned ends) are problematic: they will either have to be narrower that normal (as in TTD, for example), or need to connect to normal wires in a clever way, like in this drawing:
![Screenshot_20200806_015703](https://user-images.githubusercontent.com/7352626/89472012-2553e280-d788-11ea-953b-5d09babaa22c.png)
The blue rectangle represents a wire. If extended to the blue-hatched area, it will match both normal and diagonal wires in shape, but will intersect either, requiring special countermeasures to prevent z-fighting.

**Comment by ssieb** [comment]
I can't tell from the screenshot exactly how it was done, but it's not that difficult and no overlap is needed.  Move your blue rectangle northeast until the southwest edge lines up with the yellow corner.  Then extend the top yellow line until it intersects with the blue rectangle and fill that triangle in.  You might need to extend the length of your blue rectangle to make that work.

**Comment by ssieb** [comment]
Here's a diagram:
![corners](https://user-images.githubusercontent.com/649904/89476201-f06f6d80-d73e-11ea-83c1-bfffc7a4af37.png)

**Comment by numberZero** [comment]
@ssieb Your wire won’t form a diagonal:
![non-diagonal](https://user-images.githubusercontent.com/7352626/89478065-8e8f2200-d797-11ea-8e1e-a45dee345dff.png)

**Comment by ssieb** [comment]
Sorry, I misunderstood what you were trying to do.  I don't think that's worth the complications required to make it work, although I wonder if there's a way to make the "connected" drawtype work here.

**Comment by numberZero** [comment]
Made a PR.

> if there's a way to make the "connected" drawtype work here.

Nope, that’s for nodeboxes only. But I just found the correct shape not requiring that:
![Screenshot_20200806_160253](https://user-images.githubusercontent.com/7352626/89534913-57a02700-d7fe-11ea-9d1b-18faf9eecfcf.png)
There are no intersections and it matches both regular and diagonal insulated wires in shape. Texturing is still a challenge, however, and it won’t connect nicely to non-insulated wires, so I think that’s not what Mesecons need, but may find its uses elsewhere.
