### ISSUE TITLE
Attempt to index field 'settings' (a nil value) in mesecons/settings.lua

### ISSUE THREAD

**Issue by Kalwing** [minetest-mods/mesecons#409]
Hi,
I can't run the game on ubuntu : 
```
ERROR[main]: Error from Lua:
ERROR[main]: ...c01/.minetest/mods/mesecons-master/mesecons/settings.lua:13: attempt to index field 'settings' (a nil value)
ERROR[main]: stack traceback:
ERROR[main]: 	...c01/.minetest/mods/mesecons-master/mesecons/settings.lua:13: in function 'setting'
ERROR[main]: 	.../.minetest/mods/mesecons-master/mesecons/actionqueue.lua:60: in main chunk
ERROR[main]: 	[C]: in function 'dofile'
ERROR[main]: 	...caspc01/.minetest/mods/mesecons-master/mesecons/init.lua:60: in main chunk
```
the concerned line in settings.lua is : 
```lua
return tonumber(minetest.settings:get("mesecon."..setting) or default)
```
So it seems that minetest doesn't have a settings attribute. I installed the game with the package manager in ubuntu. My version of minetest is 0.4.13, I thought maybe it wasn't the right version for mesecon but compiling from the latest source gave me the same issue.

Didn't know if I should have posted here or on the minetest git. Sorry for the inconvenience if it isn't the right place.

**Comment by sfan5** [comment]
> My version of minetest is 0.4.13

this is way too old

> should have posted here or on the minetest git

nah, here is indeed correct

**Comment by Kalwing** [comment]
Recompiled from the latest repo, and it worked. Must have made a mistake.
Thanks for the help !
