### ISSUE TITLE
Documentation on how inactive mapblocks are handled

### ISSUE THREAD

**Issue by Hawk777** [minetest-mods/mesecons#411]
Sometimes machines get pretty big. Sometimes you don’t want to anchor everything, because that would be a lot of mapblocks. So, it would be nice to have some documentation regarding what exactly happens when a particular event happens in a mapblock at a particular state.

For example, for the Luacontroller, I could imagine a matrix (grid). There would be three columns representing the state of the mapblock containing the Luacontroller: “active” (anchored or a player is nearby), “cached” (not active but still in RAM), and “unloaded” (not in RAM). Then there would be a row for each thing that can happen to a Luacontroller: incoming Mesecons wire state change, incoming Digiline message, interrupt timer expires, etc.. Within each cell of the grid would be an explanation of what happens to that event when the Luacontroller is in a mapblock of the designated state. Presumably the entire “active” column would just say “handled immediately”, but the other columns could say something like “handled immediately” (the mapblock is loaded into RAM if needed and the code runs, regardless of whether there are players or anchors nearby), “deferred” (nothing happens, but next time a player goes near the Luacontroller, it will run the code for the event), or “dropped” (the event disappears and the code will never run).

The same information for other nodes would also be useful. For example, wire can conduct signal through even unloaded mapblocks due to using voxelmanips, but what happens at the end? If it hits a piston in an unloaded block, will the piston extend? Will it move the other nodes in front of it, or not? What about a movestone? Or, another example, if a blinky plant is in an unloaded node, will it keep blinking (I’m guessing no, but I don’t know for sure).

**Comment by numberZero** [comment]
Good idea! I needed that information often to build reliable circuits, and had to guess and to experiment (and to look through the source sometimes) to obtain it. I personally remember several points:

* Blinky plant blinks in active blocks only as it uses ABM for that.
* LuaC fully works in loaded (“cached” in your terms) blocks AFAIK, and interrupts load the block when necessary (unsure on that). Moreover, VoxelManips load blocks as well, so everything at the end will be at least loaded.

The situation is more complicated with some other nodes, though.

* For example, piston consists of 2 nodes, and pushes (or pulls) some more. The exact behavior here won’t fit in such a table.
* Node detector is even more interesting. Normally, it works in active blocks only (as it uses an ABM). But it responds to digilines in merely loaded blocks as well (and digilines load all the wire on message just like meseons IIRC), and thus *is able to detect unloaded blocks:* these are reported as `ignore` (detector has to be in another block for that to work, of course).

**Comment by Hawk777** [comment]
Yeah, pistons and movestones are complicated. They’re kind of separate nodes though, so maybe their information should be formatted a bit differently. The table makes sense for Luacontrollers because they have the three states and lots of different events, with pretty simple response to each event type. Pistons and movestones have only one event type (or maybe two, if you count pushing and pulling separately) but complicated responses to each, so maybe prose would be better than a table, or perhaps the table rows could be the different nodes (i.e. in a given mapblock state, what happens to the piston, what happens to the head, and what happens to the other nodes).

**Comment by Hawk777** [comment]
Accumulated notes for later turning into something nice:
### LuaController, by event
- program: obviously impossible to perform without a player nearby
- interrupt: occurs on schedule when active; occurs on schedule when loaded but inactive; occurs and forces loading (but not activation) of the mapblock when unloaded (luacontroller `lc_interrupt` callback calls `NodeMetaRef::get_int` which calls `NodeMetaRef::getmeta` which calls `Map::getNodeMetadata` which calls `Map::emergeBlock` which loads the block).
- on/off: occurs immediately when active or loaded but inactive; unloaded is impossible because wire will load the block before delivering the event
- digiline: occurs immediately when active or loaded but inactive; unloaded is impossible because wire will load the block before delivering the event

### Conductors
Wire, insulated wire, vertical wire, and mese blocks all load unloaded blocks on each signal edge and conduct signal through active or loaded but inactive blocks.

### Receptors
The power plant has no time-dependent behaviour, so it is impossible to observe it in an inactive or unloaded block. The blinky plant, as you say, blinks in an active block; in an inactive or unloaded block it retains its last state and resumes blinking once the block activates.

The switch, wall lever, and wall button can only be operated by a nearby player.

The solar panel only changes its output in an active block. If inactive or unloaded, it retains its previous output; when activated, if its output is incorrect for the new time of day, it immediately updates.

### Effectors
- Note block: If a note block makes a sound, but nobody is around to hear it, does it make a sound?
- Lamp, lightstone: If a lamp makes light, but nobody is around to see it, does it make light? It does end up with the correct state when you arrive later, though.
- Piston:
  - A piston that extends or withdraws in an inactive block still pushes or pulls nodes in that block.
  - A piston can’t try to extend or withdraw while it, itself, lives in an unloaded node, because the conductor would have loaded its block.
  - A piston that tries to extend its pusher *into* an unloaded block loads the block part way through processing, but the pusher replaces, rather than pushing, the block it finds there; it doesn’t actually invoke that node’s destructor, either; it just unceremoniously wipes it from existence (this happens because `ignore` is considered MVPS-replaceable, replaceables are not included in the stack to push, and then `piston_on` uses `set_node` (which seems to load the block) to place the pusher) and replaces it with the pusher.
  -  A piston that tries to withdraw its pusher from inside an unloaded block loads the block from which it is withdrawing. If the piston is sticky, it pulls the next node.
  - A piston whose pusher does not enter an unloaded block, but tries to push a node into an unloaded block, acts like the piston extending into unloaded block case above, unceremoniously wiping the node that used to exist in the unloaded block from existence and replacing it with the pushed node.
  - An extended sticky piston whose pusher is touching an unloaded block, on withdrawing, doesn’t pull anything, instead unsticking itself from the node it would normally have pulled. If it later extends and the adjacent block is loaded, it resticks.
  - If an extended piston whose pusher is in an inactive or unloaded block retracts, the node that stops being supported does not fall. If the pusher then extends with the block still being inactive or unloaded, the node remains on top of the pusher. If the block becomes active while the pusher is withdrawn, the node falls (I’m not sure why this last sentence happens, but it does).
- A movestone works like a piston with the following differences:
  - Issue #413.
  - There is no pusher, so everything that refers to the piston and pusher being in different blocks is irrelevant.
  - If a movestone tries to move from a loaded block to an unloaded block, it unceremoniously wipes from existence the node whose space it moves into, rather than pushing it.
  - A sticky movestone that tries to pull a node from an unloaded block leaves it behind, whether the block is directly or indirectly attached.
- A removestone or ghoststone disappears when powered (or reappears when unpowered, in the case of a ghoststone) in any loaded block, active or not. It cannot receive signals in an unloaded block because the wire will load the block.
- A command block (node) executes its commands in any loaded block, active or not. It cannot receive signals in an unloaded block because the wire will load the block.
- A torch only changes its state when the block containing it is active. If a torch is in an inactive block, it keeps its old state and is updated once the block activates.

### Logic
- The FPGA, gates, and the delayer behave pretty much like conductors; they work properly in inactive but loaded areas, wires bringing signals to them load them, and when they generate signals, that causes loading of the conductor to which they send output. This includes if the block containing a delayer is unloaded in between when its input changes and when it generates its output.

**Comment by Hawk777** [comment]
I think that’s all the nodes? So now we have a question: which of the described behaviours are bugs (which should be turned into issues and eventually fixed), and which are intended behaviour which should be documented?

**Comment by numberZero** [comment]
@Hawk777 https://gist.github.com/numberZero/e8ff5137ae20e1e67cda302a2aa6490a
1. Is that suitable?
2. Where to put such information?

**Comment by Hawk777** [comment]
> 1. Is that suitable?

Yes, I think that’s a good writeup. All the information looks correct (except for microcontroller, which I haven’t tested because I can’t craft one and I don’t really care enough to make one via admin commands—so I trust your writeup).

> 2. Where to put such information?

I have no idea. This isn’t my mod :smile: Maybe [the website](https://github.com/Jeija/mesecons.net)?

**Comment by numberZero** [comment]
Not my, either. I have no access to the website. I opened an [issue](https://github.com/Jeija/mesecons.net/issues/14), but chances are that it will remain unnoticed. How’s about the [wiki page](https://wiki.minetest.net/Mods/Mesecons)?

> except for microcontroller

`grep -r after mesecons_microcontroller/`

**Comment by numberZero** [comment]
@Hawk777 See also #432.

**Comment by Hawk777** [comment]
Will be unavailable for a while, sorry, but will look when I get time.

**Comment by numberZero** [comment]
https://wiki.minetest.net/Mods/Mesecons/Inactive_mapblock_handling

**Comment by Hawk777** [comment]
Thanks for putting it there, but… it still seems weird to have it on wiki.minetest.net? I would not have thought to look there for Mesecons documentation given that mesecons.net exists. I would have expected all the documentation to be on mesecons.net (though I agree that information regarding unfixed bugs could go somewhere more quickly editable, or even just in a ticket and not documented anywhere else IMO).
