### ISSUE TITLE
Movestone doesn’t drop falling nodes

### ISSUE THREAD

**Issue by Hawk777** [minetest-mods/mesecons#413]
If a movestone has a falling node on top of it and moves out of the way, the falling node doesn’t fall. Note that if a sticky movestone pulls a node behind itself out of the way of a falling node, the falling node *does* fall, it’s just if *the movestone itself* used to be supporting the falling node, then it doesn’t fall. This is because, in `movestone_move`, `mvps_pull_all` calls `check_for_falling`, but the movestone itself is handled by an explicit `set_node` and `remove_node` and `check_for_falling` is not called.

This applies to both a horizontal movestone moving sideways out from under a falling node and a vertical movestone moving down with a falling node above it. It doesn’t apply to a vertical sticky movestone because that pulls its nodes rather than letting them fall.

**Comment by numberZero** [comment]
@Hawk777 
Seems trivially fixable, can you make a PR, please?
