### ISSUE TITLE
LuaController's error function called with unexpected argument type causes server crash.

### ISSUE THREAD

**Issue by beyondlimits** [minetest-mods/mesecons#416]
```lua
error()
error(nil)
error(true)
error({})
```

**Comment by numberZero** [comment]
@beyondlimits Make sure you don’t use the same old version as OP in #417. The crash should have been fixed in 564bdc2d9b0f265b4286b3caaf8a9059953ce08b (2017-05-08).

If current `master` crashes, please provide the log with backtrace.
