### ISSUE TITLE
Uses deprecated setting functions

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/mesecons#417]
The current version (2017.03.05) uses minetest.setting_* instead of the minetest.settings object.

**Comment by numberZero** [comment]
@SnarkBoojum Where did you find that *current* version? In master, everything is fine as of f70a308bb0bddefe963a6b82016f67d3be122069 (2018-03-25).

**Comment by SnarkBoojum** [comment]
Well, it's the last official version : the latest tag. "Master" is a random commit...

**Comment by SnarkBoojum** [comment]
I would prefer a release : I'm packaging mesecons for Debian and it's better to be able to distribute something definite...

**Comment by numberZero** [comment]
That sounds nice, and I can prepare a release (if @Jeija doesn’t mind that), but... the `minetest.settings` object you mentioned is only available in Minetest 5, which is not released itself yet; so what kind of release you expect from a mod for it?

**Comment by SnarkBoojum** [comment]
Uh... the object is available in 0.4.17 as far as I know ; I already packaged a few mods using it, so I would have noticed if they hadn't work.

Perhaps the next minetest is the one where the now-deprecated api will become unsupported instead of just dumping warnings in the logs?

**Comment by numberZero** [comment]
Sorry, I missed that; minetest/minetest@18b921015a33c6e597f480bccc7e2974af33c4ea is what is not in 0.4 yet, and we don’t use that yet. So I take back my objection.

**Comment by SnarkBoojum** [comment]
Ok, then perhaps someone could tag a new release? :-p

**Comment by numberZero** [comment]
Someone could) I’m scanning through bug list right now, preparing a release)
#407 is probably the only blocker remained, and #422 fixes it, and hopefully doesn’t introduce any new problems.

**Comment by numberZero** [comment]
https://github.com/minetest-mods/mesecons/releases/tag/v1.2

**Comment by SnarkBoojum** [comment]
1.2!? Is the change in versioning scheme intentional? Previous versions followed a YYYY.MM.DD scheme.

**Comment by numberZero** [comment]
Yes, the change is intentional. Mesecons are mature enough to follow classical versioning IMO.
You can use older scheme for Debian packages ofc, if only Debian rules permit that, I don’t mind.

**Comment by SnarkBoojum** [comment]
Debian has a scheme to handle versioning scheme changes, but it's supposed to be used seldomly, so I wanted to be sure it was intentional and would be followed through before applying for it.

I'm now working on packaging 1.2 : thanks!
