### ISSUE TITLE
Something got weird ;-)

### ISSUE THREAD

**Issue by VanessaE** [minetest-mods/mesecons#426]
Something went haywire on one of my servers, I don't know exactly what...

I was having a severe lag/hang problem with that server, so I tried removing a mod here, a mod there, etc. until I got it to run "normally".  It came down to the LuaController component of mesecons.

So, figuring that the culprit wasn't really a LuaC, but perhaps something being controlled by one, I inserted a print() statement at https://github.com/minetest-mods/mesecons/blob/master/mesecons_luacontroller/init.lua#L129 just to see what LuaC's were changing state.  Maybe someone built a "lag machine", you know?

Brought it back up with all mods in place as normal, and waited.  The prints indicated that there was only one LuaC hung again.  So, I removed LuaC's from the server temporarily so that I could investigate.

When I restarted and teleported to the coordinates given by my print statement, this happened:  https://github.com/minetest-mods/technic/issues/431

So, I removed the technic_worldgen mod as well, restarted and ... there was nothing at the target location but solid stone and a few unknown nodes (just some Technic lead ore).

The server was no longer hanging up, so I restored everything back to normal and somehow, the server went back to running normally again - no more hang.

...and then I realized I had teleported to the wrong coords.  So I went to the *right* coords, found the referenced LuaC, but it wasn't doing anything unusual - just running few node breakers.

So....I leave this here because I don't know wtf went wrong, except that disabling LuaC's and technic_worldgen for a brief time, and then restoring them, without any changes, got the world working again.

**Comment by DS-Minetest** [comment]
So, without technic_worldgen, the lag stopped? What was the code of the luac? This will probably be hard to reproduce…

**Comment by VanessaE** [comment]
The lag stopped, yes, but it *remained* stopped after I re-enabled that mod.  My only conclusion is a lag machine of some sort, and that LuaC was just a red herring.  Too late now to look at it.

**Comment by DS-Minetest** [comment]
A red herirng?
Is the meta lost?

**Comment by VanessaE** [comment]
Nah, it's just long since been removed, and anyway I don't remember it was.

"Red Herring" means something that's misleading.
