### ISSUE TITLE
Case problem with LED overlay images?

### ISSUE THREAD

**Issue by sofar** [minetest-mods/mesecons#444]
https://github.com/minetest-mods/mesecons/blame/028c290cd70591383682c244a95a955fd3cba083/mesecons_luacontroller/init.lua#L745

The files are named with lowercase. Somehow, in `master` of minetest, if you download `mesecons` through the in-game mod loader, these images fail to render and are replaced with template color textures.

I suggest fixing the code to match the lower case in the file names.

**Comment by numberZero** [comment]
> I suggest fixing the code to match the lower case in the file names.

But the names are mixed-case
```
$ ls mesecons_luacontroller/textures/
jeija_luac_background.png          jeija_luacontroller_LED_A.png  jeija_luacontroller_LED_C.png  jeija_luacontroller_top.png
jeija_luacontroller_burnt_top.png  jeija_luacontroller_LED_B.png  jeija_luacontroller_LED_D.png  jeija_luac_runbutton.png
```
so probably it’s the content manager what messes the names up.
