### ISSUE TITLE
Multibyte characters lost on copy

### ISSUE THREAD

**Issue by spixi** [minetest-mods/mesecons#445]
When you insert a text into the Lua Microcontroller, select it and copy it into your clipboard with Ctrl+C, all multibyte characters are broken, as only the last byte is copied.

For example, if you insert the character "ł" (on my keyboard this is AltGr + L), it becomes "B" (U+0042 instead of U+0142).

**Comment by spixi** [comment]
This is in fact a problem, because some characters are converted to strange control characters, which can break some other mods depending on digiline.

**Comment by numberZero** [comment]
Not our bug. @spixi The fact copy-paste works at all is good, see minetest/minetest#373 (yep, that’s an old issue). For this particular problem, see minetest/minetest#6938; it’s a really wanted feature but it needs man-hours at least.
