### ISSUE TITLE
No longer possible to cancel Luacontroller interrupts

### ISSUE THREAD

**Issue by cheapie** [minetest-mods/mesecons#453]
737f366 seems to have made it no longer possible to cancel pending interrupts by setting the duration to nil.

For example, if an interrupt with IID "blah" has been set with something like interrupt(5,"blah") but has not yet executed (delay not expired yet), it was previously possible to run interrupt(nil,"blah") to cancel that interrupt. This now gives an error stating "Delay must be a number", and has made several machines that depended on this functionality stop working.

**Comment by DS-Minetest** [comment]
It was an older commit. See https://github.com/minetest-mods/mesecons/commit/737f366741f54659b17bd9c96e2232eedb9735ee#diff-0875d6fbb7ce4b468db9d73b9f3889a9L275.
I couldn't find the commit that introduced this check (I gave up in the year 2016). The interrupts probably were never canceled with this method.

**Comment by cheapie** [comment]
Yeah, I can't find it either now... I'll just close this unless someone can figure that out, and then I'll see about modifying those machines.

**Comment by numberZero** [comment]
The check was there since https://github.com/minetest-mods/mesecons/commit/0d441444219816bac6dfd3da0d3997c763bc1669 (2013). But it was silent until 737f366.
@DS-Minetest `man git blame`
