### ISSUE TITLE
Mese (trapped) chest

### ISSUE THREAD

**Issue by Extex101** [minetest-mods/mesecons#457]
Make a chest that activates mesecons when opened

**Comment by benrob0329** [comment]
I think it would be much more useful to have a comparator-type device which allows you to determined how full a chest/furnace/etc is.

**Comment by DS-Minetest** [comment]
Use the mesechest from moremesecons: https://github.com/minetest-mods/MoreMesecons/tree/master/moremesecons_mesechest

**Comment by Extex101** [comment]
Oh I never actually tried out the mesechest to see what it does...
Thanks
