### ISSUE TITLE
DUPLICATING mesecon wires in 5.0.0

### ISSUE THREAD

**Issue by Niwla23** [minetest-mods/mesecons#459]
If you place a button on a node and connect it through the node with a mesecon you dont lose your mesecon and an additional item drops! Its only in 5.0.0. I duplicated a stack to three stacks in 30 seconds!

**Comment by DS-Minetest** [comment]
I can't reproduce.
Do you have some sort of item drop mod installed? Do you use the newest mesecons version? Did you also update minetest_game? Are you sure that you don't have the creative priv?

**Comment by Niwla23** [comment]
I will make a Video

**Comment by Niwla23** [comment]
https://drive.google.com/open?id=1FPBkAYG_UbUeCnaHieo_eKrTrZqEbwt9

**Comment by Niwla23** [comment]
Sorry for the bad english

**Comment by DS-Minetest** [comment]
Ok, I could reproduce with the contentdb version.
It's actually an old version. Downloading it says that it's this commit: https://github.com/minetest-mods/mesecons/commit/7013f2e5d47ff2d21fb66fe82966a34ece947eec (15 May 2018)
Someone should update the contentdb version to the newest release [(1.2.1)](https://github.com/minetest-mods/mesecons/releases/tag/v1.2.1). I don't know, who can do this, maybe only Jeija or contentdb moderators.

**Comment by Niwla23** [comment]
@Jeija Please update the release

**Comment by benrob0329** [comment]
@rubenwardy
