### ISSUE TITLE
Quasi-Connectivity

### ISSUE THREAD

**Issue by Tarku** [minetest-mods/mesecons#460]
Can you add Quasi-Connectivity ? That is a thing that pertubated me when I started mesecons !

**Comment by benrob0329** [comment]
Oh please no. There's enough inconsistency with mesecons as it is, I really don't want to have to keep block-updates in mind as well.

**Comment by Tarku** [comment]
Ok

**Comment by DS-Minetest** [comment]
What was actually requested here? Something that just seems to be connected?¿
And what do you mean with
>pertubated

?

**Comment by benrob0329** [comment]
Its a Redstone mechanic where certain nodes will be powered from places you don't first expect, and won't notice it until a map change.
