### ISSUE TITLE
mesecons_luacontroller is broken in v1.2 with digilines installed

### ISSUE THREAD

**Issue by neoh4x0r** [minetest-mods/mesecons#467]
The commit **Limit and optimize digiline_send (#379)**
https://github.com/minetest-mods/mesecons/commit/2b096f050d8ef46ec0a669ea4e125ae79745090e)

Breaks digilines detection (in get_digiline_send), but worked prior to that commit.
See also: https://forum.minetest.net/viewtopic.php?f=11&t=5263&p=351520#p351520

It seems that the call to `minetest.global_exists("digilines")` returns nil regardless (even if digilines is installed and active).

The change was made as follows (in **Limit and optimize digiline_send**):

```
local function get_digiline_send(pos)
-	if not digiline then return end
+	if not minetest.global_exists("digilines") then return end
```

I believe it would be better to check if the global-variabe 'digilines' is nil.

To quote the commit:

> * Clean up interaction with Digilines
> 
> Use `minetest.global_exists` to avoid an undefined global variable
> warning when operating a Luacontroller with Digilines not available. Use
> the new `digilines` table in preference to the old `digiline` table.
> 

EG:
```
local function get_digiline_send(pos)
	if digilines == nil then 
		send_warning("digiline_send requires digilines to be installed/enabled.")
		return function(channel, msg)	
			return false
		end
	end
```

The properly detects digilines and has the added benefit of alerting someone that digilines is not installed (without constantly saying someting like: 'attempt to cal digiline_send (a nil value)').

**Comment by DS-Minetest** [comment]
Do you use the newest digilines version?
(The global variable "digilines" is new (2 years old) (see https://github.com/minetest-mods/digilines/commit/6a2fa5a3e49ce3612e857b39a0c12ea8420e6795).)

(And I don't really see a problem with `digiline_send` being `nil` without digilines installed.)

**Comment by neoh4x0r** [comment]
@DS-Minetest 
I'm using the latest version of digilines: https://github.com/minetest-mods/digilines/commit/434010bdd0362b79a67a07a2055d690c50d9311f
(which is 9 months newer than the linked commit).

The problem is that **minetest.global_exists("digilines")** doesn't seem to be working properly.
However, checking if **digilines == nil** does.

Futhermore, the move to **global_exists** was done "to avoid an undefined global variable
warning" as per the commit-message in https://github.com/minetest-mods/mesecons/commit/2b096f050d8ef46ec0a669ea4e125ae79745090e

This is why I suggested moving back to accessing the global directly -- using **digilines**, but not **minetest.global_exists**

**Comment by DS-Minetest** [comment]
I've tried to reproduce with newest master, but I couldn't. `digiline_send` works as expected.

How should `digilines ~= nil` be better than [`rawget(_G, "digilines") ~= nil`](https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/builtin/common/strict.lua#L12)?

**Comment by neoh4x0r** [comment]
@DS-Minetest 
I just updated minetest to the latest version (5.1) https://github.com/minetest/minetest/commit/0c319469439237ba0db31ccbffeef06e2f5ab45f

And digieline_send still fails to work with minetest.global_exists("digilines").

Obviously there shouldn't be any difference in calling:
`digilines ~= nil`
vs
`rawget(_G, "digilines") ~= nil`

However, even with the latest version of minetest, digilines, and mesecons --
digiline_send still does not work.



So, I modified the global_exists function to output 'name' to the console:

```
function core.global_exists(name)
	print("core.global_exists('" .. tostring(name) .. "')")
	if type(name) ~= "string" then
		error("core.global_exists: " .. tostring(name) .. " is not a string")
	end
	return rawget(_G, name) ~= nil
end
```

I saw several messages in the console:
```
core.global_exists('stairsplus')
core.global_exists('tubelib')
core.global_exists('moreores').
core.global_exists('unified_inventory')
core.global_exists('skytest')
core.global_exists('moretrees')
core.global_exists('basic_materials')
```

Oddly though when minetest.global_exists was called from the luacontroller in
get_digiline_send -- it never output `core.global_exists('digilines')` to the console.

So, to follow-up this is the behavior:

[**works**] if digilines == nil then return end
[**works**] if rawget(_G, "digilines") == nil then return end
[**does not work**] if not minetest.global_exists("digilines") then return end

This is looking to be a very strange problem....

**Comment by neoh4x0r** [comment]
@DS-Minetest

To update this, it seems that calling global_exists from get_digiline_send is the problem.

**If I declare the following at the top pf mesecons_luacontroller/init.lua**
`local digilines_exists = minetest.global_exists("digilines")`

**And change get_digiline_send to this:**
```
local function get_digiline_send(pos, itbl, send_warning)
   if not digilines_exists  then return end
```

Then it works as intended.

**Comment by numberZero** [comment]
That’s probably due to sandboxing. So, the check needs to be at the global scope:
`local digilines_exists = minetest.global_exists("digilines")`
but then `digilines?` must be in the dependencies (otherwise the check might fail).

**Comment by neoh4x0r** [comment]
@numberZero 
Yes, I agree that check needs to be in global scope
(and since digilines is a requirement for digiline_send to to wok, it should be in depends.txt)

**Comment by DS-Minetest** [comment]
>That’s probably due to sandboxing.

The check happens before the environment is changed. Also, I can't reproduce this problem. This is weird.
@neoh4x0r Do you use any other mod btw.?

**Comment by neoh4x0r** [comment]
@DS-Minetest 
Yes I have more than a few mods installed...(but that shouldn't have any effect on the issue)
Because when the other mods call minetest.global_exists -- they behave as expected.

I feel that sandboxing could come into play:

```
local function create_environment(pos, mem, event, itbl, send_warning)
 [...]
 local env = {
 [...]
  digiline_send = get_digiline_send(pos, itbl, send_warning),
 [...]
 }
 [...]
end
```

When a luacontroller  executes digiline_send -- it is actually calling get_digiline_send which is a runtime function and is subject to the sandbox.

**Comment by DS-Minetest** [comment]
>When digiline_send is executed it is calling get_digiline_send at runtime and is subject to the created sandbox.

No, `get_digiline_send` is called in `create_environment`. If it was called at runtime, it would look like this:
```lua
local env = {
...
digiline_send = function(...)  get_digiline_send(...) end,
...
}
```

Have you tried reproducing in a world with only mesecons and digilines installed?

**Comment by neoh4x0r** [comment]
@DS-Minetest 
> Have you tried reproducing in a world with only mesecons and digilines installed?

I just created a new world with only mesecons and digilines installed .... the issue didn't happen (it worked as expected).

So, I installed one mod at a time and narrowed it down to
 **mobf-core** from https://salsa.debian.org/games-team/minetest-mod-mobf-core

**Comment by neoh4x0r** [comment]
I'm closing this issue because the problem is not with mesecons_luacontroller.

**Comment by numberZero** [comment]
@neoh4x0r Ugh, I remember I’ve seen these stupid lines already... and have even suggested a patch a **long** time ago.

The code is not for *overriding* the function, but for *providing* it on older MT versions. But due to double negation, it does exactly the opposite. And the provided function is wrong ofc...

**Comment by DS-Minetest** [comment]
Eww, that code is ugly. `(not somestring) ~= "function"` Using not and comparators (like == or >) at the same time is so unintuitive.
