### ISSUE TITLE
Feature Request: actual Redstone equivalent ore

### ISSUE THREAD

**Issue by Tcll** [minetest-mods/mesecons#471]
I know this might sound a little nit picky
but since Mese is more similar to Minecraft's Emeralds than it is to Redstone
I'm sure villager functionality will be added in the future, and Mese will likely be used as currency just like Emeralds...

I'm not trying to claim bias or anything, I really love what this mod adds :D
just seems a bit weird to have wire based on what's essentially emeralds
so yeah, would you please consider a retake for a future redesign that adds an actual redstone equivalent :)

or maybe make use of copper or gold for more realism :)

**Comment by benrob0329** [comment]
MTG probably won't get any NPCs, ever. Mese doesn't have a use other than as lamps and tools in vanilla MTG, although other games have given it uses.

What you're suggesting is to fundamentally change what this mod is, I mean it's in the name! A fork or new mod would be where such a suggestion would be useful, perhaps on the forums although it's been asked before. There are some other tech mods which make use of other things, and the game Mineclone2 implements Redstone in a more classical way.

**Comment by DS-Minetest** [comment]
@Tcll I think, you misunderstood mese. It has nothing to do with minecraft's emeralds. The mese crystals have formed in more recent years, the primal form of mese is what is now called "mese block" (try `/giveme mese`). I think, I've never seen mese being used as currency. Mese is a somewhat alien thing. [And there's evidence that mesecons really works.](https://forum.minetest.net/viewtopic.php?f=3&t=5369)

>the game Mineclone2 implements Redstone in a more classical way.

Mineclone2 uses mesecons, see https://repo.or.cz/MineClone/MineClone2.git/tree/HEAD:/mods/ITEMS/REDSTONE.

**Comment by Tcll** [comment]
> What you're suggesting is to fundamentally change what this mod is
trust me, I'm very much aware what I'm suggesting ;)
I DID think myself through before asking, but that doesn't mean I have all the knowledge in the world yet about Mese.

the reason I was sugesting a change was because you already have a large community behind it with a lot of work done already, and creating another mod just to move an entire community over to wouldn't exactly be ideal

> Mese is a somewhat alien thing.

I did consider this a possibility before asking, but wasn't aware  this was actually the case
(lol at that thread)

> the game Mineclone2 implements Redstone in a more classical way.
> Mineclone2 uses mesecons

ah so there is an origin and it's not just a new conceptual use

alright, I'm sorry for my lack of knowledge :)

I've just come here straight from Minecraft, so I'm still just getting my ropes on things
this is MUCH bigger than I thought it was
thanks for the references :)

**Comment by DS-Minetest** [comment]
> EDIT: also, thanks for not being Ds about my suggestion

Off course I'm not Ds, I'm DS. What do you mean with Ds?

**Comment by Tcll** [comment]
> Off course I'm not Ds, I'm DS. What do you mean with Ds?

I don't cuss ;)
