### ISSUE TITLE
mesecon.mergetable semantics is unclear

### ISSUE THREAD

**Issue by numberZero** [minetest-mods/mesecons#483]
The documentation states, it doesn’t overwrite values, and appends values with numerical keys. But in fact things are more complicated.

For example, if a non-numerical key is present in either table, the corresponding value is deep-copied. But if it is present in both, it is referenced from `dest` instead, *unless* the value in `dest` is `false` which gets overwritten.

With numerical keys, things aren’t better either; it’s probably better to rewrite this function than to investigate the exact ways in which it misbehaves currently.

https://github.com/minetest-mods/mesecons/blob/15e743629e60fd7b588383c4fd855d51d1859693/mesecons/util.lua#L215-L227

**Comment by DS-Minetest** [comment]
Can [`table.insert_all(table, other_table)`](https://github.com/minetest/minetest/blob/d77ea764768f5cde9e8f0781356a67d723aa7609/doc/lua_api.txt#L2752-L2754) be used?

**Comment by numberZero** [comment]
No, that’s for arrays only.

**Comment by numberZero** [comment]
I just realized there is a problem. What should `mergetable` do if numerical indices are discontinuous? And how should it find that out, remembering that `ipairs` may stop after *any* non-nil position followed by nil, not necessarily first or last such one.

**Comment by numberZero** [comment]
> Maybe table.insert_all(table, other_table) can be used.

It can actually, in most places where `mergetable` is used. The others don’t require the `ipairs` part.

**Comment by HybridDog** [comment]
```lua
print("\nrules.default:")
for i,v in ipairs(mesecon.rules.default) do
	print(("[%d] = %s"):format(i, minetest.pos_to_string(v)))
end
print("\nrules.floor:")
for i,v in ipairs(mesecon.rules.floor) do
	print(("[%d] = %s"):format(i, minetest.pos_to_string(v)))
end
```

```
rules.default:
[1] = (0,0,-1)
[2] = (1,0,0)
[3] = (-1,0,0)
[4] = (0,0,1)
[5] = (1,1,0)
[6] = (1,-1,0)
[7] = (-1,1,0)
[8] = (-1,-1,0)
[9] = (0,1,1)
[10] = (0,-1,1)
[11] = (0,1,-1)
[12] = (0,-1,-1)

rules.floor:
[1] = (0,-1,0)
[2] = (1,0,0)
[3] = (-1,0,0)
[4] = (0,0,1)
[5] = (1,1,0)
[6] = (1,-1,0)
[7] = (-1,1,0)
[8] = (-1,-1,0)
[9] = (0,1,1)
[10] = (0,-1,1)
[11] = (0,1,-1)
[12] = (0,-1,-1)
[13] = (0,0,-1)
[14] = (1,0,0)
[15] = (-1,0,0)
[16] = (0,0,1)
[17] = (1,1,0)
[18] = (1,-1,0)
[19] = (-1,1,0)
[20] = (-1,-1,0)
[21] = (0,1,1)
[22] = (0,-1,1)
[23] = (0,1,-1)
[24] = (0,-1,-1)
```
