### ISSUE TITLE
Issue on Minetest 0.4.13

### ISSUE THREAD

**Issue by AnontheAnonomys** [minetest-mods/mesecons#498]
"Attempt to index field "Settings" (A nil value):
[debug.txt](https://github.com/minetest-mods/mesecons/files/3935585/debug.txt)

I don't understand lua a bit so I can't debug this on my own, if this is an issue faced by others, please let me know

System Details:
OS: Linux Mint 18.2 Sonya
CPU: Intel Pentium 1.87 GHz
RAM: 1024 MB 
Chassis: Lenovo Thinkpad R61i

Other mods installed:
Included
Worldedit
Pipeworks
Moreblocks
Moreores

**Comment by benrob0329** [comment]
0.4.13 was released over 4 years ago. 5.1.0 is the current version, please update.

**Comment by AnontheAnonomys** [comment]
Uhm... I can't update libc6

**Comment by ssieb** [comment]
> 0.4.13 was released over 4 years ago. 5.1.0 is the current version, please update.

How did you find that or do you just recognize the output?  I was trying to figure out which version he was using, but didn't see any indication.

**Comment by AnontheAnonomys** [comment]
I'm using Minetest 0.4.13, the latest availible on Synaptic

**Comment by Calinou** [comment]
You can install the Minetest Flatpak from Flathub: https://www.flathub.org/apps/details/net.minetest.Minetest

**Comment by AnontheAnonomys** [comment]
Ah, I'm on Mint.

**Comment by AnontheAnonomys** [comment]
and upgrading will take too much time outta my day

**Comment by ssieb** [comment]
If you won't update minetest, then you can't update the mods either.  You'll need to get a version of the mod that's that old as well.

**Comment by benrob0329** [comment]
You shouldn't need to update libc if Mint is being reasonable about library versions.
There is a PPA for Ubuntu and Mint anyways: https://www.minetest.net/downloads/

**Comment by SmallJoker** [comment]
mesecons requires 5.0.0+ to work as intended. If you revert 1bf862f it might also work with 0.4.17.1 (last 0.4.x release).

5.2.0-dev works fine on my laptop which has roughly the same specs.
