### ISSUE TITLE
Lua controller code editor improvenments

### ISSUE THREAD

**Issue by BruceMustache** [minetest-mods/mesecons#518]
Improve lua controntroller editor:
  * code highlighting
  * tab insert tabulators or 4 spaces
  * show lines

Any ideas can put here

**Comment by numberZero** [comment]
Impossible. Minetest is not a general-purpose GUI platform, it has [formspecs](https://github.com/minetest/minetest/blob/f92a393f6f949377b1d78630a8f7d24e78e6ff9d/doc/lua_api.txt#L1991) only.

**Comment by BruceMustache** [comment]
@numberZero There is a way to customize text using formspec
`minetest.colorize` and `style[]`
https://github.com/minetest/minetest/blob/f92a393f6f949377b1d78630a8f7d24e78e6ff9d/doc/lua_api.txt#L2986

**Comment by numberZero** [comment]
These features might let you perform syntax highlighting on the code when the server sends it, but not during editing. That would require either native implementation, or decent CSM support. Current CSM state is unusable: “Transferring client-sided mods from the server to the client is planned, but not implemented yet.”

So better, use your favorite editor and copy-paste, it *should* work (e.g. on my system, Ctrl+V works usually but Shift+Ins doesn’t).

**Comment by BruceMustache** [comment]
Can you make the formspec code send by server do highlight while in editing
Like setting callbacks inside idk

**Comment by numberZero** [comment]
The formspec code is not executable, it only *describes* the GUI. There are no callbacks, each button just sends the form contents to the server (there are nuances ofc but they won’t help). That’s much like a HTML form in pre-JS days, if you know these. Oh, and each time the server replies to update it, the whole form will be replaced with what it sends, resetting editing position at the very least.
