### ISSUE TITLE
Server crash - fix suggestion

### ISSUE THREAD

**Issue by za267** [minetest-mods/mesecons#520]
Our server is crashing with:

```
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'biome_lib' in callback environment_Step(): /home/someguy/.minetest/mods/mesecons/mesecons/presets.lua:68: attempt to index local 'dir' (a nil value)
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]: stack traceback:
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         /home/someguy/.minetest/mods/mesecons/mesecons/presets.lua:68: in function 'getAnyInputRules'
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         /home/someguy/.minetest/mods/digilines/internal.lua:45: in function 'rules_link'
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         /home/someguy/.minetest/mods/digilines/internal.lua:114: in function 'transmit'
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         /home/someguy/.minetest/mods/digilines/init.lua:53: in function 'receptor_send'
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         .../.minetest/mods/mesecons/mesecons_luacontroller/init.lua:691: in function <.../.minetest/mods/mesecons/mesecons_luacontroller/init.lua:685>
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         ...someguy/.minetest/mods/mesecons/mesecons/actionqueue.lua:137: in function 'execute'
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         ...someguy/.minetest/mods/mesecons/mesecons/actionqueue.lua:111: in function <...someguy/.minetest/mods/mesecons/mesecons/actionqueue.lua:73>
Jul 27 16:13:25 aurelium-dev minetestserver[567050]: 2020-07-27 16:13:25: ERROR[Main]:         /usr/local/share/minetest/builtin/game/register.lua:419: in function </usr/local/share/minetest/builtin/game/register.lua:399>
```

We put a temporary fix in by adding  a 'not null' check on 'dir':

```
local function rules_from_dir(ruleset, dir)
+       if not dir then return end
        if dir.x ==  1 then return ruleset.xp end
        if dir.y ==  1 then return ruleset.yp end
        if dir.z ==  1 then return ruleset.zp end
        if dir.x == -1 then return ruleset.xn end
        if dir.y == -1 then return ruleset.yn end
        if dir.z == -1 then return ruleset.zn end
end
```

**Comment by sfan5** [comment]
This was determined to be a mod issue the last time this was discussed, see #496.

**Comment by za267** [comment]
@sfan5 hum, what do you mean it's a mod issue?  Isn't mesecons a mod?

**Comment by sfan5** [comment]
Sorry, that was unclear. <i>Mod issue</i> that a mod other than mesecons is at fault here.

**Comment by za267** [comment]
@sfan5 Ah right makes sense... Yeah I think biome lib might be the one doing it, not 100% sure though.   I thought I'd let you know just in case you felt like adding some validation of input since I believe this is basically an API?

**Comment by numberZero** [comment]
@za267 That’s called “defensive programming.” That is, there is a requirement to use `wallmounted_get` on `wallmounted` nodes only, and `buttonlike_get` on `facedir` nodes only. You suggest to tolerate violations of these requirements, returning `nil` in that case. That’s possible ofc but “make it foolproof, and someone will invent a better fool.” E.g. some day, a caller may crash seeing that `nil` instead of a table.

However, it’s possible to replicate the `facedir_to_dir` and `wallmounted_to_dir` logic; that should be faster (no need to construct the table only to check it then) and should never crash.

**Comment by za267** [comment]
@numberZero Yeah that sounds reasonable... may as well let it crash, this way you know where you are going wrong when you are using it incorrectly.

**Comment by numberZero** [comment]
Not our bug. It’s pretty clear that `wallmounted_get` is only to be used on `wallmounted` nodes. It’s less clear was the function intended to be used outside Mesecons at all.
