### ISSUE TITLE
Improve the mesecon torches

### ISSUE THREAD

**Issue by ghost** [minetest-mods/mesecons#531]
Torches that are hanging from walls shouldn't be powered from below, it makes it almost impossible to build a ROM

**Comment by numberZero** [comment]
@KrzysztofJeszke Screenshot please, I don’t quite understand your problem.

**Comment by Desour** [comment]
@KrzysztofJeszke 
I guess with "from below" you mean from behind the wall.
You might want to use powerplants instead of torches. Those are always on.

**Comment by numberZero** [comment]
The issue is unclear, and the author doesn’t and won’t respond (his account is deleted).
