### ISSUE TITLE
Feature request - Gated D latch

### ISSUE THREAD

**Issue by donno2048** [minetest-mods/mesecons#542]
Since I started using this mod I have built the D latch too many time:
<img width="322" alt="Screenshot 2020-10-09 024445" src="https://user-images.githubusercontent.com/61805754/95524375-dde11100-09d9-11eb-91ae-989db3349797.png">

**Comment by OgelGames** [comment]
This can be made using a microcontroller with the code `if(C)sbi(B,A);`

![screenshot_20210113_221831](https://user-images.githubusercontent.com/48543043/104445798-ae036400-55ed-11eb-8100-677a3873aa53.png)
