### ISSUE TITLE
Luacontroller - Timer interrupt causes overheating

### ISSUE THREAD

**Issue by mase76** [minetest-mods/mesecons#549]
Hi!
A timer interrupt in my program causes a luacontroller overheating after a few seconds.
I use this interrupt to toggle a port every second.
For testing I replaced my interrupt with the example from https://mesecons.net/luacontroller

interrupt(0.5, "a parameter")
print(event.iid)

Even with 1 second, this also causes an overheating.
No other commands are executed at this time.

**Comment by cheapie** [comment]
I haven't had any problems like this - what is this LuaC hooked up to, and is there any other code in it at all?

**Comment by mase76** [comment]
No more code.

**Comment by mase76** [comment]
I found out, that modlib causes the luacontroller overheating.
Deactivated modlib and it works.
-- 
gpg: 383107c4
