### ISSUE TITLE
Add support for locales

### ISSUE THREAD

**Issue by ltworf** [minetest-mods/mesecons#550]
Hello,

I had forked this project to contribute an italian translation, but I then realised that there is no locale support at all.

So, just asking if it would be possible to provide it.

**Comment by lolbinarycat** [comment]
this seems fixed?

**Comment by Niklp09** [comment]
Added in https://github.com/minetest-mods/mesecons/commit/2ede29df9c34ee85cde894b2aada979ff38453ca
