### ISSUE TITLE
Wires going into FPGAs never turn off

### ISSUE THREAD

**Issue by sfan5** [minetest-mods/mesecons#559]
Following setup:
`[FPGA] [wire]`
Gate config:
`  = C -> A`

Put a power plant next to the wire, remove the plant again and observe how the wire is still on?!

Broken by #556 @Desour I'm pretty sure I tested this before but I guess not .

**Comment by Desour** [comment]
Uh, I'm very sorry.
Fix: #560
It turned out that one loop wasn't completely useless, but was used to check non-emptiness of an array-style table.
