### ISSUE TITLE
No release since december 2018: forgotten tags?

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/mesecons#577]
There has been many changes but no release since december 2018 ; does that mean all those changes are unstable, or that you forgot to tag releases?

**Comment by sfan5** [comment]
Mesecons gets "releases" uploaded to [ContentDB](https://content.minetest.net/packages/Jeija/mesecons/releases/) every few months (no idea who does it).
If it's convenient for packaging purposes I'm sure these could be tagged in git too.

**Comment by SnarkBoojum** [comment]
Additionally, that would make it clearer which commit ended up in ContentDB too.

**Comment by sfan5** [comment]
Release created.
