### ISSUE TITLE
using a piston on a bed causes it to become unbreakable.

### ISSUE THREAD

**Issue by stormchaser3000** [minetest-mods/mesecons#579]
Hello,

I recently came back to Minetest and started an anarchy server. Well, needless to say, there was a game breaking bug discovered when one of the players on my server was playing with pistons (as there almost always is on such a server). It turns out that using a piston or sticky piston on a bed causes it to become invincible as it's selection box disappears (you can no-longer point at it).

It appears that for some odd reason, one side of the bed seems to be merged with the other and the game gets confused. I don't know if I should report this here or to the minetest_game repo, but I figured I would start here.

EDIT: it is also worth noting that you can still walk on the bed as normal.

here is a screenshot, and I will look through the logs to see if there is anything useful in there.

![screenshot_20211128_201614](https://user-images.githubusercontent.com/6621537/143798526-a25a85c8-9425-428f-a508-c4a3bb87dab3.png)

**Comment by auouymous** [comment]
Pushing the bed from the ends works fine, but pushing from the sides causes this to happen. You can place a second bed next to the broken bed and push the missing half into it to make the first bed whole again. The second bed is now broken, but pushing the missing half back into the second bed will make the second bed whole and remove the first bed completely.

**Comment by mazes-80** [comment]
> Pushing the bed from the ends works fine, but pushing from the sides causes this to happen. You can place a second bed next to the broken bed and push the missing half into it to make the first bed whole again. The second bed is now broken, but pushing the missing half back into the second bed will make the second bed whole and remove the first bed completely.

From what I see, it only appears to work visually, if you remove the bed_bottom the bed_top will still not be removed from the world. Whatever side, piston do not care of attaches or callbacks that are allowing to have a unique bed, it always splits bed in two independent parts and bed_top is not even pointable.

**Comment by Desour** [comment]
Multi-node stuff should be made mvps stoppers, this includes beds and also wooden doors.
