### ISSUE TITLE
Torch logic directional bug

### ISSUE THREAD

**Issue by VorTechnix** [minetest-mods/mesecons#580]
The torch only deactivates if powered from below on the -X axis
![image](https://user-images.githubusercontent.com/45538536/149996042-f67e1327-a954-4ec2-842c-8178784b13af.png)

Otherwise it does nothing
![image](https://user-images.githubusercontent.com/45538536/149996188-487a8d93-8eb8-4bb8-8bb1-51a8ab1f29cc.png)

The bug happens with any activation source be it other torches, mesecon lines or insulated lines
![image](https://user-images.githubusercontent.com/45538536/149996530-cdb31d35-57b6-4e18-a0e4-eeb4074a51ef.png)
![image](https://user-images.githubusercontent.com/45538536/149997026-74ee6bc4-701c-4012-9bce-e8697dd55fe1.png)
 
I'm using Minetest 5.4.1, Singleplayer mode.

**Comment by sfan5** [comment]
Can you try an older mesecons version (from 2020) and see if it happens there? Would help determine whether this is a regression.

**Comment by VorTechnix** [comment]
Sure,

**Comment by VorTechnix** [comment]
Tried 2020-11-06 [d356f] created 2020-11-06 with a clean world and no other mods. Same bug.
![image](https://user-images.githubusercontent.com/45538536/150010686-2ca7724c-5d14-4e17-8230-e78a0d82a3d3.png)
