### ISSUE TITLE
Luacontroller can be abused to massively fill up server memory up to crash

### ISSUE THREAD

**Issue by appgurueu** [minetest-mods/mesecons#597]
Consider the following example of exponential string concatenation:

```lua
local s = "x"; for _ = 1, 1000 do s = s .. s end
```

Press "execute" a few times, watch the memory usage rise to ridiculous levels and your system killing the process in response.

Mitigation would most likely require a RAM-limited subprocess for execution; keeping track of the memory used through local variables and `debug.getlocal` might work as well, but would slow execution down to a crawl (would have to be checked every step).

**Comment by Desour** [comment]
Duplicate of #516?

**Comment by appgurueu** [comment]
> Duplicate of #516?

Yes. GH issue search didn't find that. Closing.
