### ISSUE TITLE
#607 broke stuff

### ISSUE THREAD

**Issue by fluxionary** [minetest-mods/mesecons#613]
#607 broke stuff for servers which use basic_materials, which is many, because it's been around forever and many mods depend on it. #607 now adds a second kind of silicon, and breaks things that depend on that material from basic_materials. #607 also caused #611. Making the mod "independent from MTG" shouldn't have broken servers that *use* MTG, and yet it has. This is part of a broader effort  to "remove dependencies", but by breaking functionality of servers currently running MTG (see e.g. https://github.com/mt-mods/homedecor_modpack/pull/28 and some other changes by people in mt-mods to mods they've adopted). 

See also #440

**Comment by TurkeyMcMac** [comment]
I don't recall adding a second kind of silicon. I'm pretty sure Mesecons has had its own silicon for a while that basic_materials overrides. Crafting with silicon still works for me when basic_materials is enabled (using Minetest 5.4.1.)

#611 was caused by an engine bug.

**Comment by fluxionary** [comment]
I may have just been caught in a bad mood when I created this, I'll look into the origin of the issue on my tomorrow.

**Comment by fluxionary** [comment]
I think you are correct. I think basic_materials's alias stopped working because the dependency ordering changed and things now load in a different order, closing this, and apologies.
