### ISSUE TITLE
hydroturbine/init.lua:67: attempt to index a nil value

### ISSUE THREAD

**Issue by Festus1965** [minetest-mods/mesecons#617]
server 5.5.o0 / mtg 5.5.0

[Mod] mesecons (0d9e027/28.02.2022)

022-06-05 09:18:11: 
ERROR[Main]: 

ServerError: AsyncErr: Lua: Runtime error from mod 'mesecons_hydroturbine' in callback LuaABM::trigger(): ...test/bin/../mods/mesecons/mesecons_hydroturbine/init.lua:67: attempt to index a nil value
stack traceback:
...test/bin/../mods/mesecons/mesecons_hydroturbine/init.lua:67: in function 'is_flowing_water'
...test/bin/../mods/mesecons/mesecons_hydroturbine/init.lua:77: in function 'func'
...mas/minetest/bin/../builtin/profiler/instrumentation.lua:107: in function <...mas/minetest/bin/../builtin/profiler/instrumentation.lua:100>

today 2 times crash as gamer use it, twice happen at same gamer, just after restart again
deactivated until ... solution

**Comment by sfan5** [comment]
Fixed by 58305f52bced0f5cdb7c4a0d27d05b04d4f379b6
