### ISSUE TITLE
Mesecons wires not conducting

### ISSUE THREAD

**Issue by Alatarius** [minetest-mods/mesecons#641]
The wires only seem to conduct in creative mode. If I switch to regular mode then the wires stop conducting. If I switch back to creative the the wires start conducting again. How can I fix this?

**Comment by numberZero** [comment]
Works for me:
* minetest-mods/mesecons@54de66b3e195a68cc28c1be6a01be3853c5d30aa
* no other mods
* minetest/minetest_game@8d60e85dfc25dffbcfb2bf30cd57de0c5f38b97b
* minetest/minetest@2a1bc82887a214b658240f8656dbe97e2e6be0cb

Please tell:
* Mesecons version
* the game you use it with, and its version
* other mods used in the world
* Minetest version

and attach a screenshot of the problem.

Also you can try to disable other mods, that may help.

**Comment by Alatarius** [comment]
Mesecons version is the latest on ContentDB (updated yesterday Apr 29 2023.
Mintest v 5.7.0

Mods used are digilines, Mesecons and pipeworks
Using it in base game.

Have video, but to capture issue makes file bigger than 10mb

**Comment by Alatarius** [comment]
creative mode vid link: https://drive.google.com/file/d/1GCf9V3lWBIx2eyI0z8xBqISHziSIJmJC/view?usp=share_link

normal mode vid link: https://drive.google.com/file/d/1_YVn_vsLVFYp-1UIUWACOWqZOgRJPZbR/view?usp=share_link

**Comment by numberZero** [comment]
Links don’t open, require signup.

**Comment by numberZero** [comment]
> Using it in base game.

What is “base game”? `devtest`? `minetest_game`?

**Comment by Alatarius** [comment]
base game is what you get when you download mt

**Comment by Alatarius** [comment]
Not sure how to get videos to you

**Comment by numberZero** [comment]
> Not sure how to get videos to you

Found an ancient Google account I have but the link still doesn’t open. Did you allow access for “anyone with the link”?

**Comment by Alatarius** [comment]
Fixed the share permissions

**Comment by numberZero** [comment]
It doesn’t stop conducting. A detector pipe is stuck in the “on” state, jamming the wire effectively (Mesecon devices act on off→on transition typically which can’t happen if the wire is constantly on). And it doesn’t depend on creative mode, it gets stuck if it is on when you exit the game. Report to [pipeworks](https://github.com/mt-mods/pipeworks).

**Comment by numberZero** [comment]
Note: if you press F5 you will be able to see some debug info including the technical name of the node you point at, e.g. `pipeworks:detector_tube_off_3` and `pipeworks:detector_tube_on_3`.

**Comment by Alatarius** [comment]
Thank you I will contact them with this issue.
