### ISSUE TITLE
MineClonia/MineClone compatibility

### ISSUE THREAD

**Issue by nonfreegithub** [minetest-mods/mesecons#650]
These Mesecons mods are compatible with MineClonia/MineClone:

- mesecons_powerplant
- mesecons_blinkyplant
- mesecons_gamecompat
- mesecons_fpga
- mesecons_switch
- mesecons_hydroturbine
- mesecons_detector
- mesecons_materials
- mesecons_microcontroller
- mesecons_random
- mesecons_luacontroller

you can install MineClonia/Mineclone and activate these mods and you will see that they work well except because the blocks cannot be dug.

the other Mesecons mods create conflict with MCL mods and it is difficult to make them compatible because MCL game already has **forks** of these mods.

dig groups are the problem.

It is simple to allow to dig these blocks in MCL simply by adding:

to:  `groups = { ... , handy=1, pickaxey=1}`

and params:

```lua
minetest.register_node("... ", {
...
_mcl_blast_resistance = 1,
_mcl_hardness = 0.7,
...
})
```

If you prefer I can do it by sending a PR, it does not create conflict with MTG

**Comment by sfan5** [comment]
> because Mineclone game already has **forks** of these mods.

We can't fix this, can we?

> dig groups are the problem.
> and params:

This could be made portable in a way similar to how [mesecons_gamecompat](https://github.com/minetest-mods/mesecons/tree/master/mesecons_gamecompat) works.

**Comment by nonfreegithub** [comment]
> > because Mineclone game already has **forks** of these mods.
> 
> We can't fix this, can we?
> 
Mmm maybe with
```lua
if minetest.get_modpath("mcl_core") then
minetest.override_item(item1, item2)
end
```

> This could be made portable in a way similar to how [mesecons_gamecompat](https://github.com/minetest-mods/mesecons/tree/master/mesecons_gamecompat) works.

yes but I dunno how
