### ISSUE TITLE
Unintuitive change: checking a number for string type

### ISSUE THREAD

**Issue by SwissalpS** [minetest-mods/mesecons#680]
If anything this should check for number not string and then ``meta:set_int()``
https://github.com/minetest-mods/mesecons/blame/d52eac5a4afec3d68f39224a8da541b3ba52b561/mesecons_detector/init.lua#L226

Having to pass a number as a string is not intuitive at all. This is even worse than the zero based-ness of this value.

In lua indexes begin with 1 not 0 and I can't think of any other node that treats distance this way. Everywhere else radius/distance of 0 is the node itself, a radius of 1 are the ~~eight~~ 26 nodes around it and a distance of 1 a node next to it.

It may be too late to change to 1-based distance, but IMO the distance field should be treated as a number not a string.

_(It is ruining my automated blueberry fields because the code used to accept a number for the distance field, but now the number is ignored and the wrong nodes are being dug. These blueberry leaves can't be dug and placed, they need to be grown in place or moved using pistons and similar.)_

Sorry for the forceful tone, I admit I'm venting a bit.

**Comment by sfan5** [comment]
0c7bb316c7df0be7b99b492d2b22b84425c87b09 | #670

**Comment by SwissalpS** [comment]
The traceback shows that the error was thrown for using ``meta:set_string()`` with a table as value.
I agree with type checking, but not for string. 

The value is then correctly read as int.
https://github.com/minetest-mods/mesecons/blob/d52eac5a4afec3d68f39224a8da541b3ba52b561/mesecons_detector/init.lua#L205

Wouldn't it be correct to check the digiline ``msg.distance`` for an integer and then use ``meta:set_int()``?

**Comment by SwissalpS** [comment]
Thank you.
