### ISSUE TITLE
crash when trying to sleep

### ISSUE THREAD

**Issue by amiant** [minetest-mods/mesecons#687]
error code

`AsyncErr: Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...bin\..\games\mesecraft\mods\mesecraft_beds/functions.lua:100: bad argument #1 to 'set_physics_override' (table expected, got number)
stack traceback:
	[C]: in function 'set_physics_override'
	...bin\..\games\mesecraft\mods\mesecraft_beds/functions.lua:100: in function 'lay_down'
	...bin\..\games\mesecraft\mods\mesecraft_beds/functions.lua:171: in function 'on_rightclick'
	...win64\bin\..\games\mesecraft\mods\mesecraft_beds/api.lua:110: in function 'on_rightclick'
	...0-win64\luanti-5.10.0-win64\bin\..\builtin\game\item.lua:344: in function <...0-win64\luanti-5.10.0-win64\bin\..\builtin\game\item.lua:337>`

**Comment by Niklp09** [comment]
Hi, the crash is caused in mesecraft's `mesecraft_beds` mod, it's not the fault of mesecons.
Mesecraft beds is using `player_obj:set_physics_override()` in an undocumented way that was removed in Luanti 5.9.0.

Engine commit: https://github.com/minetest/minetest/commit/c524c52baa5456cff87127b3c4c41b5758b91c7a
More information: https://github.com/Archtec-io/bugtracker/issues/179
