### ISSUE TITLE
Entity and node move order

### ISSUE THREAD

**Issue by mruncreative** [minetest-mods/mesecons#693]
I think moving node entity combinations that are in one position is currently very cumbersome. Maybe there already is a good solution, maybe something could be changed.

**Comment by mruncreative** [comment]
Here's an example of what I imagine should work but doesn't and duplicates the entity.

```
local function get_entity(pos)
	local objects = core.get_objects_inside_radius(pos, 0.5)
	local found
	for _, obj in ipairs(objects) do
		if obj and obj:get_luaentity() and obj:get_luaentity().name == "issue:entity" then
			found = obj
			break
		end
	end
	return found
end

core.register_node("issue:node", {
	description = "issue",
	tiles = {"wool_white.png"},
	groups = {oddly_breakable_by_hand = 1},
	on_destruct = function(pos)
		local o = get_entity(pos)
		if o then o:get_luaentity():on_activate() end
	end,
	on_construct = function(pos)
		local o = get_entity(pos)
		if not o then core.add_entity(pos, "issue:entity") end
	end,
})


core.register_entity("issue:entity", {
	initial_properties = {
		physical = true,
		visual = "sprite",
		textures = {"default_wood.png"},
		collisionbox = {-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
		selectionbox = {-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},--{0, 0, 0, 0, 0, 0},
	},
	on_activate = function(self, staticdata, dtime_s)
		if core.get_node(self.object:get_pos()).name ~= "issue:node" then
			self.object:remove()
		end
	end,

})
```

**Comment by Desour** [comment]
Mesecons has callbacks for when nodes and entities are moved, see functions in <https://github.com/minetest-mods/mesecons/blob/master/mesecons_mvps/init.lua>, and <https://github.com/minetest-mods/mesecons/blob/5883a0ce65f0ee2c62cfa9372c93d933bba835ee/mesecons_mvps/init.lua#L336>.

**Comment by mruncreative** [comment]
Great, I didn't know that. Is that documented somewhere?

**Comment by Desour** [comment]
I think it is not. (Also not [here](https://mesecons.net/developers.html).)

**Comment by mruncreative** [comment]
The order in which entities and node are moved and on_construct on_destruct and on_mvps_move are called seems to be different in VoxeLibre. For some reason I can't get it to work in both MTG and VoxeLibre

**Comment by mruncreative** [comment]
Is there one for objects too?
